name: GitHub Pages CI/CD

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7
      - name: Jekyll build
        run: | 
          bundle exec jekyll build
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 2.7

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Tests
      run: bundle exec rake test  # replace with your actual test command

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 2.7

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        cname: your-custom-domain  # optional, replace with your actual custom domain

  merge-check:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
    - name: Check Pull Request Status
      run: |
        # Check if the current pull request has the required status checks passing
        pr_status=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/status" | jq -r '.state')

        if [ "$pr_status" != "success" ]; then
          echo "Error: Required status checks not passing. Cannot merge pull request."
          # Provide feedback by adding a comment on the pull request
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"body": "❌ The CI/CD checks failed. Please review the build logs."}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
          exit 1
        else
          echo "Success: All checks passed. Pull request can be merged."
          # Provide feedback by adding a comment on the pull request
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"body": "✅ The CI/CD checks passed. Ready for review and merge."}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
        fi
